name: go-test
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: v1.26.1
      - name: Install just
        run: sudo apt update && sudo apt install -y just
      - name: Run Tests
        run: |
          just test
