CREATE TABLE IF NOT EXISTS rss_feed(id INTEGER PRIMARY KEY AUTOINCREMENT,
url TEXT UNIQUE NOT NULL,
title TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS rss_item(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  feed_id INT NOT NULL REFERENCES rss_feed(id),
  guid TEXT UNIQUE NOT NULL,
  link TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL
);
