// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Migration struct {
	Name      string       `db:"name"`
	AppliedAt sql.NullTime `db:"applied_at"`
}

type RSSFeed struct {
	ID    int64  `db:"id"`
	Url   string `db:"url"`
	Title string `db:"title"`
}

type RSSItem struct {
	ID          int64  `db:"id"`
	FeedID      int64  `db:"feed_id"`
	Guid        string `db:"guid"`
	Link        string `db:"link"`
	Title       string `db:"title"`
	Description string `db:"description"`
	Pushed      int64  `db:"pushed"`
}

type Room struct {
	ID    string `db:"id"`
	State string `db:"state"`
}

type User struct {
	ID   string `db:"id"`
	Role string `db:"role"`
}
