// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Event struct {
	ID      int64  `db:"id"`
	EventID string `db:"event_id"`
	RoomID  string `db:"room_id"`
}

type Migration struct {
	Name      string     `db:"name"`
	AppliedAt *time.Time `db:"applied_at"`
}

type RSSFeed struct {
	ID      int64  `db:"id"`
	Url     string `db:"url"`
	Title   string `db:"title"`
	EventID *int64 `db:"event_id"`
}

type RSSItem struct {
	ID          int64  `db:"id"`
	FeedID      int64  `db:"feed_id"`
	Guid        string `db:"guid"`
	Link        string `db:"link"`
	Title       string `db:"title"`
	Description string `db:"description"`
	Pushed      int64  `db:"pushed"`
}

type Room struct {
	ID    string `db:"id"`
	State string `db:"state"`
}

type User struct {
	ID   string `db:"id"`
	Role string `db:"role"`
}
