// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Migration struct {
	Name      string       `db:"name"`
	AppliedAt sql.NullTime `db:"applied_at"`
}

type RssFeed struct {
	ID    int64  `db:"id"`
	Url   string `db:"url"`
	Title string `db:"title"`
}

type RssItem struct {
	ID          int64  `db:"id"`
	FeedID      int64  `db:"feed_id"`
	Guid        string `db:"guid"`
	Link        string `db:"link"`
	Title       string `db:"title"`
	Description string `db:"description"`
}
