// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	SelectFeedByID(ctx context.Context, id int64) (RssFeed, error)
}

var _ Querier = (*Queries)(nil)
