// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room.sql

package db

import (
	"context"
)

const createRoom = `-- name: CreateRoom :exec
INSERT
    OR IGNORE INTO room (id, state)
        VALUES (?, ?)
`

type CreateRoomParams struct {
	ID    string `db:"id"`
	State string `db:"state"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg *CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom, arg.ID, arg.State)
	return err
}

const isRoomExists = `-- name: IsRoomExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            room
        WHERE
            id = ?)
`

func (q *Queries) IsRoomExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRoomExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isRoomJoined = `-- name: IsRoomJoined :one
SELECT
    state = 'accept'
FROM
    room
WHERE
    id = ?
`

func (q *Queries) IsRoomJoined(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRoomJoined, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const isRoomLeft = `-- name: IsRoomLeft :one
SELECT
    state = 'leave'
FROM
    room
WHERE
    id = ?
`

func (q *Queries) IsRoomLeft(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isRoomLeft, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateRoomState = `-- name: UpdateRoomState :exec
UPDATE
    room
SET
    state = ?
WHERE
    id = ?
`

type UpdateRoomStateParams struct {
	State string `db:"state"`
	ID    string `db:"id"`
}

func (q *Queries) UpdateRoomState(ctx context.Context, arg *UpdateRoomStateParams) error {
	_, err := q.db.ExecContext(ctx, updateRoomState, arg.State, arg.ID)
	return err
}
