// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rss_feed.sql

package db

import (
	"context"
)

const allFeeds = `-- name: AllFeeds :many
SELECT
    id, url, title, event_id
FROM
    rss_feed
ORDER BY
    id
`

func (q *Queries) AllFeeds(ctx context.Context) ([]RSSFeed, error) {
	rows, err := q.db.QueryContext(ctx, allFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RSSFeed
	for rows.Next() {
		var i RSSFeed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRSSFeed = `-- name: CreateRSSFeed :exec
INSERT INTO rss_feed (url, title)
    VALUES (?, ?)
`

type CreateRSSFeedParams struct {
	Url   string `db:"url"`
	Title string `db:"title"`
}

func (q *Queries) CreateRSSFeed(ctx context.Context, arg *CreateRSSFeedParams) error {
	_, err := q.db.ExecContext(ctx, createRSSFeed, arg.Url, arg.Title)
	return err
}

const deleteRSSFeed = `-- name: DeleteRSSFeed :exec
DELETE FROM rss_feed
WHERE id = ?
`

func (q *Queries) DeleteRSSFeed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRSSFeed, id)
	return err
}

const getFeedThreadRootEventByID = `-- name: GetFeedThreadRootEventByID :one
SELECT
    e.id,
    e.event_id,
    e.room_id
FROM
    event AS e
    INNER JOIN rss_feed AS f ON e.id = f.event_id
WHERE
    f.id = ?
`

func (q *Queries) GetFeedThreadRootEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getFeedThreadRootEventByID, id)
	var i Event
	err := row.Scan(&i.ID, &i.EventID, &i.RoomID)
	return i, err
}

const selectFeedByID = `-- name: SelectFeedByID :one
SELECT
    id, url, title, event_id
FROM
    rss_feed
WHERE
    id = ?
LIMIT 1
`

func (q *Queries) SelectFeedByID(ctx context.Context, id int64) (RSSFeed, error) {
	row := q.db.QueryRowContext(ctx, selectFeedByID, id)
	var i RSSFeed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.EventID,
	)
	return i, err
}

const updateFeedThreadRootEventByID = `-- name: UpdateFeedThreadRootEventByID :exec
UPDATE
    rss_feed
SET
    event_id = ?
WHERE
    id = ?
`

type UpdateFeedThreadRootEventByIDParams struct {
	EventID *int64 `db:"event_id"`
	ID      int64  `db:"id"`
}

func (q *Queries) UpdateFeedThreadRootEventByID(ctx context.Context, arg *UpdateFeedThreadRootEventByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedThreadRootEventByID, arg.EventID, arg.ID)
	return err
}
