// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rss_item.sql

package db

import (
	"context"
)

const createRSSItem = `-- name: CreateRSSItem :one
INSERT
    OR IGNORE INTO rss_item (feed_id, guid, link, title, description)
        VALUES (?, ?, ?, ?, ?)
    RETURNING
        id
`

type CreateRSSItemParams struct {
	FeedID      int64  `db:"feed_id"`
	Guid        string `db:"guid"`
	Link        string `db:"link"`
	Title       string `db:"title"`
	Description string `db:"description"`
}

func (q *Queries) CreateRSSItem(ctx context.Context, arg *CreateRSSItemParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createRSSItem,
		arg.FeedID,
		arg.Guid,
		arg.Link,
		arg.Title,
		arg.Description,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteRSSItemByFeedID = `-- name: DeleteRSSItemByFeedID :exec
DELETE FROM rss_item
WHERE feed_id = ?
`

func (q *Queries) DeleteRSSItemByFeedID(ctx context.Context, feedID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRSSItemByFeedID, feedID)
	return err
}

const markRSSItemPushedByID = `-- name: MarkRSSItemPushedByID :exec
UPDATE
    rss_item
SET
    pushed = 1
WHERE
    id = ?
`

func (q *Queries) MarkRSSItemPushedByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markRSSItemPushedByID, id)
	return err
}
