// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rss_feed.sql

package db

import (
	"context"
)

const allFeds = `-- name: AllFeds :many
SELECT
  id, url, title
FROM
  rss_feed
ORDER BY
  id
`

func (q *Queries) AllFeds(ctx context.Context) ([]RssFeed, error) {
	rows, err := q.db.QueryContext(ctx, allFeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RssFeed
	for rows.Next() {
		var i RssFeed
		if err := rows.Scan(&i.ID, &i.Url, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRSSFeed = `-- name: CreateRSSFeed :exec
INSERT INTO rss_feed(
  url,
  title
)
VALUES(
  ?,
  ?
)
`

type CreateRSSFeedParams struct {
	Url   string `db:"url"`
	Title string `db:"title"`
}

func (q *Queries) CreateRSSFeed(ctx context.Context, arg *CreateRSSFeedParams) error {
	_, err := q.db.ExecContext(ctx, createRSSFeed, arg.Url, arg.Title)
	return err
}

const deleteRSSFeed = `-- name: DeleteRSSFeed :exec
DELETE FROM rss_feed
WHERE
  id = ?
`

func (q *Queries) DeleteRSSFeed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRSSFeed, id)
	return err
}

const selectFeedByID = `-- name: SelectFeedByID :one
SELECT
  id, url, title
FROM
  rss_feed
WHERE
  id = ?
LIMIT 1
`

func (q *Queries) SelectFeedByID(ctx context.Context, id int64) (RssFeed, error) {
	row := q.db.QueryRowContext(ctx, selectFeedByID, id)
	var i RssFeed
	err := row.Scan(&i.ID, &i.Url, &i.Title)
	return i, err
}
