// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rss_item.sql

package db

import (
	"context"
)

const createRSSItem = `-- name: CreateRSSItem :exec
INSERT
OR IGNORE INTO rss_item(feed_id,
guid,
link,
title,
description)
VALUES(?,
?,
?,
?,
?)
`

type CreateRSSItemParams struct {
	FeedID      int64  `db:"feed_id"`
	Guid        string `db:"guid"`
	Link        string `db:"link"`
	Title       string `db:"title"`
	Description string `db:"description"`
}

func (q *Queries) CreateRSSItem(ctx context.Context, arg *CreateRSSItemParams) error {
	_, err := q.db.ExecContext(ctx, createRSSItem,
		arg.FeedID,
		arg.Guid,
		arg.Link,
		arg.Title,
		arg.Description,
	)
	return err
}

const deleteRSSItemByFeedID = `-- name: DeleteRSSItemByFeedID :exec
DELETE FROM rss_item
WHERE
  feed_id = ?
`

func (q *Queries) DeleteRSSItemByFeedID(ctx context.Context, feedID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRSSItemByFeedID, feedID)
	return err
}
