// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
)

const allUsers = `-- name: AllUsers :many
SELECT
    id, role
FROM
    user
`

func (q *Queries) AllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, allUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: CreateUser :exec
INSERT
    OR IGNORE INTO user (id, role)
        VALUES (?, ?)
`

type CreateUserParams struct {
	ID   string `db:"id"`
	Role string `db:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.Role)
	return err
}

const isUserAdmin = `-- name: IsUserAdmin :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            user
        WHERE
            id = ?
            AND role = 'admin')
`

func (q *Queries) IsUserAdmin(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserAdmin, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const selectUserByID = `-- name: SelectUserByID :one
SELECT
    id, role
FROM
    user
WHERE
    id = ?
LIMIT 1
`

func (q *Queries) SelectUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const updateUserRoleByID = `-- name: UpdateUserRoleByID :exec
UPDATE
    user
SET
    role = ?
WHERE
    id = ?
`

type UpdateUserRoleByIDParams struct {
	Role string `db:"role"`
	ID   string `db:"id"`
}

func (q *Queries) UpdateUserRoleByID(ctx context.Context, arg *UpdateUserRoleByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRoleByID, arg.Role, arg.ID)
	return err
}
